### ISSUE TITLE
Assign tasks to eyepopper

### ISSUE THREAD

**Issue by eyepopper** [BluePlay-Games/rules#24]
### **Give me a job or something idk**

**Comment by saverofthewos** [comment]
Do you have experience in any programming languages other than scratch?

**Comment by npxl32** [comment]
@eyepopper

**Comment by eyepopper** [comment]
A little bit of Lua

**Comment by eyepopper** [comment]
@saverofthewos specifically ROBLOX lua

**Comment by npxl32** [comment]
> @saverofthewos specifically ROBLOX lua

You should learn some C#

**Comment by eyepopper** [comment]
why? what are we working on

**Comment by npxl32** [comment]
We're making games in Godot with C#. [Game ideas go here.](https://github.com/BluePlay-Games/rules/discussions/21)
